name:                haskell-gi-template
version:             0.1.0.0
github:              "Harmos274/haskell-gi-template"
license:             BSD3
author:              "Lilian VERLHAC"
maintainer:          "lilian.verlhac@outlook.com"
copyright:           "2021 Lilian VERLHAC"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-gi-template#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- haskell-gi-base
- gi-gtk == 3.0.*

library:
  source-dirs: src

executables:
  haskell-gi-template-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-gi-template

tests:
  haskell-gi-template-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-gi-template
